### ISSUE TITLE
Draft Legislation - Open Data Index

### ISSUE THREAD

**Issue by infokujur** [okestonia/Estonian-Open-Data-Issue-Tracker#6] opened 2017-02-16 15:14 UTC
Data about the bills discussed within national parliament as well as votings on bills (not to mix with passed national law). Data on bills must be available for the current legislation period.

- Content of bill
- Author of bill
- Votes on bill per member of parliament
- Transcripts of debates on bill
- Status of bill

http://global.survey.okfn.org/dataset/draftlegislation

**Comment by andreskytt** [comment] 2017-03-19 17:51
Duplicate of #30 . Closing

**Closed by andreskytt** 2017-03-19 17:51 UTC
