### ISSUE TITLE
Crime Data

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/Estonian-Open-Data-Issue-Tracker#33] opened 2017-03-10 15:23 UTC
Crime data we currently have is by year, type, and at the linnaosa level.

Having access to crime data by distinct date would be beneficial, also if possible to have more accurate location information ex :https://data.cityofchicago.org/view/5cd6-ry5g

**Comment by andreskytt** [comment] 2017-03-13 09:44
Seems like a duplicate of #14 Close, if so

**Comment by keeganmcbride** [comment] 2017-03-13 09:52
Duplicate --closed

**Closed** 2017-03-13 09:52 UTC
